const SCHEDULE_DATA: ScheduleEaaantry[] = [
    { round: 1, home: { m: "M3", w: "W3" }, away: { m: "M1", w: "W4" } },
    { round: 2, home: { m: "M3", w: "W4" }, away: { m: "M4", w: "W1" } },
    { round: 3, home: { m: "M1", w: "W2" }, away: { m: "M4", w: "W1" } },
    { round: 4, home: { m: "M2", w: "W2" }, away: { m: "M3", w: "W4" } },
    { round: 5, home: { m: "M3", w: "W3" }, away: { m: "M4", w: "W4" } },
    { round: 6, home: { m: "M2", w: "W3" }, away: { m: "M1", w: "W1" } },
    { round: 7, home: { m: "M2", w: "W4" }, away: { m: "M1", w: "W2" } },
    { round: 8, home: { m: "M4", w: "W3" }, away: { m: "M3", w: "W2" } },
    { round: 9, home: { m: "M2", w: "W4" }, away: { m: "M3", w: "W1" } },
    { round: 10, home: { m: "M2", w: "W1" }, away: { m: "M4", w: "W3" } },
    { round: 11, home: { m: "M4", w: "W2" }, away: { m: "M1", w: "W3" } },
    { round: 12, home: { m: "M1", w: "W2" }, away: { m: "M3", w: "W1" } },
    { round: 13, home: { m: "M4", w: "W4" }, away: { m: "M2", w: "W3" } },
    { round: 14, home: { m: "M3", w: "W2" }, away: { m: "M2", w: "W1" } },
    { round: 15, home: { m: "M3", w: "W4" }, away: { m: "M1", w: "W3" } },
    { round: 16, home: { m: "M2", w: "W1" }, away: { m: "M1", w: "W3" } },
    { round: 17, home: { m: "M4", w: "W1" }, away: { m: "M2", w: "W4" } },
    { round: 18, home: { m: "M1", w: "W4" }, away: { m: "M4", w: "W2" } },
    { round: 19, home: { m: "M3", w: "W2" }, away: { m: "M2", w: "W3" } },
    { round: 20, home: { m: "M4", w: "W4" }, away: { m: "M1", w: "W1" } },
    { round: 21, home: { m: "M2", w: "W2" }, away: { m: "M4", w: "W3" } },
    { round: 22, home: { m: "M1", w: "W4" }, away: { m: "M2", w: "W2" } },
    { round: 23, home: { m: "M3", w: "W3" }, away: { m: "M1", w: "W1" } },
    { round: 24, home: { m: "M3", w: "W1" }, away: { m: "M4", w: "W2" } }
  ];